version: "3.9"
services:
  client:
    build: ./frontendweb
    container_name: client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:80"
  api:
    build: ./backendgo
    volumes:
      - /app/node_modules
      - ./server:/app
    container_name: api
    ports:
      - "8080:80"
  database:
    image: mysql:5.7
    container_name: database

    restart: always

    volumes:
      - ./dbvol:/var/lib/mysql

    environment:
      MYSQL_DATABASE: 'icsg'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

    ports:
      - "3306:3306"

    expose:
      - "3306"

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8000:80"
    environment:
      - SERVER_ADDRESS=localhost
      - BACKEND_ADDRESS=backend
      - FRONTEND_ADDRESS=website
    depends_on:
      - client
      - api
